
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/software/cmake-3.29.2-windows-x86_64/cmake-3.29.2-windows-x86_64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:9 (PROJECT)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
...
